permalink: /:categories/:year/:month/:title
highlighter: rouge
gems:
  - jekyll-redirect-from
navigation:
  - title: home
    url: /
  - title: source
    url: "https://github.com/JuliaLang/julia"
  - url: "/downloads/"
    title: downloads
  - url: "http://docs.julialang.org/"
    title: docs
  - url: "http://pkg.julialang.org/"
    title: packages
  - url: "/blog/"
    title: blog
  - url: "/community/"
    title: community
  - url: "/learning/"
    title: learning
  - url: "/teaching/"
    title: teaching
  - url: "/publications/"
    title: publications
  - url: "/soc/"
    title: GSoC
  - url: "http://juliacon.org"
    title: juliacon
featuredvideos:
  - site: youtube
    id: B9moDuSYzGo
    title: "Solving the Two Language Problem"
  - site: youtube
    id: gQ1y5NUD_RI
    title: "Introduction to Julia for Scientific Computing - David Sanders"
  - site: youtube
    id: rAxzR7lMGDM
    title: "Intermediate Julia - David Sanders"
  - site: youtube
    id: EeKs_seYz6U
    title: "What R can learn from Julia"
  - site: youtube
    id: e6-hcOHO0tc
    title: "Gallium - the Julia Debugger"
baseurl: "julialang.github.com"
